import type { Metadata } from "next";
import { Geist, Geist_Mono, Google_Sans } from "next/font/google";
import "./globals.css";
import ChatScreen from "./components/chat-screen";

const google_sans = Google_Sans({
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${ google_sans.className } h-full antialiased`}
    >
      <body className="min-h-full flex flex-col h-full">
        <div className="h-full">
          <ChatScreen/>
        </div>
      </body>
    </html>
  );
}
